version: '3.7'

services:
  postgres:
    image: postgres:16.4
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - pgdata:/data/postgres
    env_file:
      - ./.env.example

  app:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./apps/grupo-primo-backend-test/Dockerfile
    ports:
      - '3000:3000'

    volumes:
      - ./apps:/usr/src/apps
      - ./libs:/usr/src/libs

    depends_on:
      - postgres

    command: npm run start:dev
    env_file:
      - ./.env.example

volumes:
  pgdata:
    driver: local
